name: PixySpawners
version: 0.9.0
main: com.pixylt.pixyspawners.PixySpawners
api-version: 1.16
commands:
  pixyspawners:
    description: Main PixySpawners command
    usage: "Usage: /pixyspawners"
  spawners:
    aliases: spawner
    description: Spawners command
    usage: "Usage: /spawners"
permissions:
  pixyspawners.*:
    default: op
    children:
      pixyspawners.help: true
  pixyspawners.help:
    default: true
